auth_enabled: false

server:
  http_listen_port: 3101
  grpc_listen_port: 9095

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 2
      heartbeat_timeout: 1m
    final_sleep: 0s
    min_ready_duration: 15s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_chunk_age: 30m
  flush_check_period: 30s
  chunk_target_size: 1048576
  flush_op_timeout: 10m
  chunk_encoding: gzip
  wal:
    dir: /loki/wal
    enabled: true

limits_config:
  retention_period: 7d
  ingestion_rate_mb: 32
  ingestion_burst_size_mb: 64
  max_streams_per_user: 1000000
  max_global_streams_per_user: 2000000
  max_line_size: 2MB
  max_query_length: 721h
  max_query_parallelism: 32
  max_streams_matchers_per_query: 1000
  max_concurrent_tail_requests: 10
  max_entries_limit_per_query: 20000
  max_cache_freshness_per_query: 1m
  max_queriers_per_tenant: 10
  allow_structured_metadata: false

schema_config:
  configs:
    - from: 2020-10-15
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index-cache
    cache_ttl: 24h
    resync_interval: 5m
  filesystem:
    directory: /loki/chunks

memberlist:
  bind_port: 7946
  advertise_port: 7946
  join_members:
    - distributor:7946
    - ingester-1:7946
    - ingester-2:7946
    - ingester-3:7946
    - index-gateway:7946
