server:
  http_listen_port: 9080
  grpc_listen_port: 0
  http_server_read_timeout: 300s
  http_server_write_timeout: 300s
  health_check_target: true

positions:
  filename: /loki/data/positions.yaml
  sync_period: 10s

clients:
  - url: http://distributor:3100/loki/api/v1/push
    batchwait: 1s
    batchsize: 1048576
    timeout: 10s

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*.log
  pipeline_stages:
    - json:
        expressions:
          timestamp: timestamp
          level: level
          message: message
    - timestamp:
        source: timestamp
        format: RFC3339Nano
    - labels:
        level:
    - output:
        source: message
  relabel_configs:
    - source_labels: [__path__]
      regex: '.*/([^/]+)\.log'
      target_label: log_file
    - source_labels: [__path__]
      regex: '/var/log/([^/]+)/.*'
      target_label: log_directory
