auth_enabled: false

common:
  compactor_grpc_address: compactor:9095

server:
  http_listen_port: 3103
  grpc_listen_port: 9095



query_range:
  align_queries_with_step: true
  max_retries: 5
  cache_results: true
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

frontend:
  compress_responses: true
  log_queries_longer_than: 5s
  downstream_url: http://querier:3102

limits_config:
  retention_period: 7d
  ingestion_rate_mb: 32
  ingestion_burst_size_mb: 64
  max_streams_per_user: 1000000
  max_global_streams_per_user: 2000000
  max_line_size: 2MB
  max_query_length: 721h
  max_query_parallelism: 32
  max_streams_matchers_per_query: 1000
  max_concurrent_tail_requests: 10
  max_entries_limit_per_query: 20000
  max_cache_freshness_per_query: 1m
  max_queriers_per_tenant: 10
  allow_structured_metadata: false

schema_config:
  configs:
    - from: 2020-10-15
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index-cache
    cache_ttl: 24h
    resync_interval: 5m
  filesystem:
    directory: /loki/chunks
